### ISSUE TITLE
Get price returns success : False

### ISSUE THREAD

**Issue by nickbijmoer** [Aareksio/node-steam-market-pricing#1]
Hello, if i want to view the price of this item i get success : false, some other items give false too, not only this item. Any1 knows a fix?

http://steamcommunity.com/market/priceoverview/?currency=1&appid=730&market_hash_name=XM1014%20|%20Blue%20Spruce

**Comment by ClockRide** [comment]
You must use item quality for example: http://steamcommunity.com/market/priceoverview/?currency=1&appid=730&market_hash_name=XM1014%20|%20Blue%20Spruce%20(Minimal%20Wear)
