### ISSUE TITLE
Item Price Undefined

### ISSUE THREAD

**Issue by crimsonwind** [Aareksio/node-steam-market-pricing#3]
Hello there! I don't know what had happen but the price are returning as undefined when previously it was working. Maybe because I keep launching the script?

This is what it looks like after I launch the script to fetch the price:

★ Shadow Daggers | Safari Mesh (Minimal Wear) : undefined
★ Shadow Daggers | Forest DDPAT (Battle-Scarred) : undefined
★ Shadow Daggers | Rust Coat (Battle-Scarred) : undefined
★ Shadow Daggers | Boreal Forest (Field-Tested) : undefined
★ Shadow Daggers | Forest DDPAT (Field-Tested) : undefined
★ Shadow Daggers | Safari Mesh (Field-Tested) : undefined
★ Shadow Daggers | Safari Mesh (Minimal Wear) : undefined

Thanks in advance!

**Comment by Aareksio** [comment]
You are probably using v2 branch with callbacks. Either change your code to use async or Promises, or keep using v1 branch.

To install v1:
```
npm install steam-market-pricing@1
```

**Comment by crimsonwind** [comment]
Thanks! My apologies for the trouble I'm quite new to this. =D Good day!
