### ISSUE TITLE
http error when market.getItemPrice(stuff) is used

### ISSUE THREAD

**Issue by woepertjes** [Aareksio/node-steam-market-pricing#5]
my code:
`else {
            logger.info('Tradeoffer received from a stranger. His/her/its steam64ID is: ' + offer.partner.getSteamID64());
            var i = 0;
            var j = 0;
            var ourItems = offer.itemsToGive;
            var theirItems = offer.itemsToReceive;
            for (; i < ourItems.length; i++) {
                var item = ourItems[i].market_hash_name;
                var appid = ourItems[i].appid;
                var ourValue = market.getItemPrice(appid[i], item[i]);
                var sum = sum + ourValue
                logger.error(item);
                logger.error(ourValue);
                logger.error(sum);
                logger.warn(market.getItemPrice(appid[i], item[i]))

                }
            for (; j < theirItems.length; j++) {
                var item2 = theirItems[j].market_hash_name;
                var appid2 = theirItems[j].appid;
                var theirValue = theirValue + market.getItemPrice(appid2[j], item2[j]);
                var sum2 = sum2 + theirValue
                logger.error(item2);
                logger.error(theirValue);
                logger.error(sum2);
                logger.warn(market.getItemPrice(appid2[j], item2[j]));
                logger.warn()
                }
                logger.warn('Offer handled. Code 12');`
Starts at line 870

the code has for loops to run through all the items in the trade offer.

The errors i'm getting are:
(node:3596) UnhandledPromiseRejectionWarning: HTTPError: Response code 400 (Bad
Request)
    at stream.catch.then.data (F:\va\node_modules\steam-market-pr
icing\node_modules\got\index.js:386:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

And

(node:3596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)

I get these errors multiple times.

it only happens if it goes for the market.getItemPrice.

You got any ideas aareksio?

**Comment by woepertjes** [comment]
some logger.error()''s are there to show me if it handled the code correctly or not. At the moment logger.err() is the only one which gets stored in a file.

**Comment by Aareksio** [comment]
You need to resolve the promise returned by this function via either `await` or `.then()`, you should handle errors properly too (`try {} catch {}` or `.catch()`).

The error is HTTP Error 400, my guess is that you're not passing proper appid / market_hash_name combination. Remember the name needs to be market name, not item name.
