### ISSUE TITLE
how to save list of items to json file

### ISSUE THREAD

**Issue by ursarik** [Aareksio/node-steam-market-pricing#6]
tried this 

const market = require('steam-market-pricing');
const fs = require('fs');

const names = [
  'MP9 | Storm (Minimal Wear)',
  'Sawed-Off | Origami (Well-Worn)'
];

market.getItemsPrices(730, names).then(items => {
  fs.writeFileSync('./items.json', items , 'utf-8');
});

result 
[object Object]

**Comment by Aareksio** [comment]
`fs.writeFileSync(file, content)` requires `content` to be a string, you are passing an Object.

To stringify an Object you can use `JSON.stringify`.
