### ISSUE TITLE
Error using required ES6 if i dont use the method required[], i got the error use required[]

### ISSUE THREAD

**Issue by theduodecim** [Aareksio/node-steam-market-pricing#8]
**Using async and required :**
function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function PricesMarket() {
    await sleep(6000);
    var moduleName = 'steam-market-pricing';
    const names = [
        'MP9 | Storm (Minimal Wear)',
        'Sawed-Off | Origami (Well-Worn)'
    ];
    require([moduleName], function (fooModule) {
        fooModule.getItemsPrices(730, names).then(items => names.forEach(name => console.log(`${name}: ${items[name].median_price}`)));
    });

}
PricesMarket();

Error
require.js:5 Uncaught Error: Script error for "steam-market-pricing"
GET http://127.0.0.1:5500/steam-market-pricing.js net::ERR_ABORTED 404 (Not Found)
req.load @ require.js:5
load @ require.js:5
load @ require.js:5
fetch @ require.js:5
check @ require.js:5
enable @ require.js:5
enable @ require.js:5
(anonymous) @ require.js:5
(anonymous) @ require.js:5
each @ require.js:5
enable @ require.js:5
init @ require.js:5
(anonymous) @ require.js:5
setTimeout (async)
req.nextTick @ require.js:5
s @ require.js:5
requirejs @ require.js:5
PricesMarket @ market.js:92
require.js:5 Uncaught Error: Script error for "steam-market-pricing"

**code alone** 
const market = require('steam-market-pricing');
market.getItemPrice(730, 'MP9 | Storm (Minimal Wear)').then(item => console.log(item));

Uncaught Error: Module name "steam-market-pricing" has not been loaded yet for context: _. Use require([])

**Comment by Aareksio** [comment]
```js
GET http://127.0.0.1:5500/steam-market-pricing.js net::ERR_ABORTED 404 (Not Found)`
```
This is not a module issue.
You seem to be trying to use the module in client app, which won't work anyway because of CORS.
